repos: 
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: sphinx-api
        name: sphinx-api
        entry: sphinx-apidoc -f -e -o docs/source xenopict -T 
        language: system
        always_run: true
        pass_filenames: false
