# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


orbs:
  python: circleci/python@2.1.1

jobs:
  test-py3.9:
    docker:
      - image: python:3.9
    steps:
      - checkout  
      - run: /usr/local/bin/python -m pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
      - run: python -m pytest 
  test-py3.10:
    docker:
      - image: python:3.10
    steps:
      - checkout  
      - run: /usr/local/bin/python -m pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
      - run: python -m pytest 

  build_test_upload:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run: /usr/local/bin/python -m pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
      - run: |
          python -m pytest 
          pip install twine
          twine upload dist/*
workflows:
  build_test_publish:
    jobs:
      - test-py3.10
      - test-py3.9
      - build_test_upload:
          requires:
            - test-py3.9
            - test-py3.10
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/

